### PR TITLE
Unify alignment

### PR DESCRIPTION
**Pull request by JohnMcGuinness**
This mostly addresses the #299 with the exception of updating WFlowLayout. @marksreeves are you able to provide some advice about adding Orientation and updating Alignment for WFlowLayout.

PTAL @jonathanaustin, if its ok with you i would like to have this merged and address WFlowLayout later after Mark provides advice.

### CODE REVIEW

**Comment by marksreeves** [comment]
I have no issues with melding Aligmnent for all of the "column" components but we need more discussion about FlowLayout. 

I think the notion of separating Orientation from Alignment is worthy in that it gives us six arrangements of components rather than the current four. The additional arrangements are: `VERTICAL` + `CENTER` and `VERTICAL` + `RIGHT`. I have seen a few UIs where `VERTICAL` + `CENTER` has been used with two nested FlowLayouts so this could be advantageous even though those particular UIs were rather poor examples as the centred content caused usability issues (and were rather ugly but that is, of course, just my personal taste).

Even if we decide to go down this route though this is a non-backwards-compatible API change so cannot be merged until after we release 1.0.3.

@jonathanaustin @ricksbrown do we have any idea when we can build 1.0.3? We promised it early this month (Jan 2016).

**Comment by marksreeves** [comment]
@JohnMcGuinness Could you also have a think about an upgrade tool: if we make this API change it is going to have a massive impact on all consumers.

**Comment by jonathanaustin** [comment]
Have added comments to #299.

**Comment by JohnMcGuinness** [comment]
Just want to check what the concenus is before I update this PR.

Based on discussion in this PR and #299 this is what I propose to do:

* Rename `Alignment` to `CellAlignment` and include all 9 values.
* Remove the `Orientation` enum
* Add a new API that uses the `CellAlignment` values, and deprecate the 'old' `Alignment` enums and related methods.
* Leave FlowLayout as is, for now.

WDYT @jonathanaustin @marksreeves @ricksbrown 

@jonathanaustin If you would like I can have a go to create `HorizontalLayout` as in #329.

**Comment by JohnMcGuinness** [comment]
@jonathanaustin PTAL I'm pretty sure this is ready to merge, based on various comments in #299 and this PR.

**Comment by JohnMcGuinness** [comment]
@jonathanaustin any chance you look at this soon?

**Comment by JohnMcGuinness** [comment]
@jonathanaustin any idea if/when this will be merged?

**Pull request closed without merging**
